---
- hosts: database
  become: true
  tasks:
    - name: install web components
      apt:
        name:
          - python-mysqldb
          - mysql-server
          - htop
        state: present
        update_cache: yes

    - name: ensure mysql started
      service: name=mysql state=started enabled=yes

    - name: ensure mysql listening on 0.0.0.0
      lineinfile: dest=/etc/mysql/my.cnf regexp=^bind-address line="bind-address = 0.0.0.0"
      notify: restart mysql

    - name: create demo database
      mysql_db: name=demo state=present

    - name: create demo user
      mysql_user: name=demo password=demo priv=demo.*:ALL host='%'

  handlers:
    - name: restart mysql
      service: name=mysql state=restarted
