---
- name: install web components
  apt:
    name:
      - python-mysqldb
      - mysql-server
      - htop
    state: present
    update_cache: yes

- name: ensure mysql listening on 0.0.0.0
  lineinfile: dest=/etc/mysql/my.cnf regexp=^bind-address line="bind-address = 0.0.0.0"
  notify: restart mysql

- name: ensure mysql started
  service: name=mysql state=started enabled=yes

- name: create database
  mysql_db: name={{db_name}} state=present

- name: create user
  mysql_user: name={{db_user_name}} password={{db_user_pass}} priv={{db_name}}.*:ALL host='%' host='{{db_user_host}}' state=present
