---
- hosts: database
  become: true
  tasks:
    - name: install web components
      apt:
        name:
          - mysql-server
          - htop
        state: present
        update_cache: yes

    - name: ensure mysql started
      service: name=mysql state=started enabled=yes
